@startuml
start
:Пользователь открывает портал;
:Вводит логин и пароль;
if (Аутентификация успешна?) then (Да)
    :Отображение главной страницы;
    :Пользователь вводит запрос поиска;
    :Система выполняет поиск в базе данных;
    :Отображение списка книг;
    if (Пользователь выбирает книгу?) then (Да)
        :Отображение деталей книги;
    else (Нет)
        :Возврат к поиску;
    endif
else (Нет)
    :Отображение ошибки входа;
    stop
endif
stop
@enduml
