@startuml
package "Книжная лавка" {
  [Клиентская часть: HTML/CSS/JS] --> [Интерфейс пользователя]
[Клиентская часть: HTML/CSS/JS] --> [Серверная часть: FastApi]
  [Серверная часть: FastApi] --> [API для поиска и управления]
  [Серверная часть: FastApi] --> [Логика обработки запросов]
  [База данных: PostgreSQL] --> [Хранилище данных о книгах]
  [База данных: PostgreSQL] --> [Хранилище данных пользователей]

  [Серверная часть: FastApi] --> [База данных: PostgreSQL]
}
@enduml
