"""Initial migration

Revision ID: 47b92dd9ed8e
Revises:
Create Date: 2025-04-08 07:15:15.158861

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47b92dd9ed8e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name_categories", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name_categories"), "categories", ["name_categories"], unique=True)
    op.create_table(
        "tegs",
        sa.Column("name_tag", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tegs_name_tag"), "tegs", ["name_tag"], unique=True)
    op.create_table(
        "books_categories",
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("categories_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["categories_id"],
            ["categories.id"],
        ),
    )
    op.create_table(
        "books_tags",
        sa.Column("book_id", sa.Integer(), nullable=True),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tegs.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books_tags")
    op.drop_table("books_categories")
    op.drop_index(op.f("ix_tegs_name_tag"), table_name="tegs")
    op.drop_table("tegs")
    op.drop_index(op.f("ix_categories_name_categories"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
